#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()
env.Append(CPPPATH = env['TOP'])

libbgp_inetmvpn = env.Library('bgp_inetmvpn',
                           ['inetmvpn_route.cc',
                            'inetmvpn_table.cc',
                            ])

env.SConscript('test/SConscript', exports='BuildEnv', duplicate = 0)
