# -*- mode: python; -*-
#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#
# src directory

import os
import re
import sys

Import('BuildEnv')

#
# platform independent python packages
#
CfgmEnv = BuildEnv.Clone()
subdirs = ['api-server']
for sdir in subdirs:
    CfgmEnv.SConscript(sdir + '/SConscript',
                       exports='CfgmEnv',
                       variant_dir = '#build/noarch/config/' + sdir,
                       duplicate = 1)

#
# TODO: makes these conform to the scheme above
#
subdirs=['uve',
         'common',
         'schema-transformer',
         'svc-monitor',
         'vnc_openstack',
         'test'
         ]

for sdir in subdirs:
    CfgmEnv.SConscript(
        sdir + '/SConscript',
        exports='CfgmEnv',
        variant_dir = CfgmEnv['TOP'] + '/config/' + sdir,
        duplicate = 0)
