# -*- mode: python; -*-
#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#
# src directory

import os
import re
import sys

Import('BuildEnv')

CfgmEnv = BuildEnv.Clone()
CfgmEnv.SConscript(dirs=['api-server'], exports='CfgmEnv',
                   variant_dir='build/noarch', duplicate = 1)

CfgmEnv.SConscript(
    dirs=['uve',
          'common',
          'schema-transformer',
          'svc-monitor',
          'vnc_openstack',
          'test'],
    exports='CfgmEnv',
#   variant_dir=CfgmEnv['TOP'] + '/config',
    duplicate = 0)
